##
## ======
## Spring
## ======
##
spring.application.name=real-estate-management
spring.profiles.active=dev
##
## =========================
## Data Source to PostgreSQL
## =========================
##
spring.datasource.url=jdbc:postgresql://localhost:5432/homestor
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=hs
##
## ===
## JPA
## ===
##
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
##
## ===========
## Host & Port
## ===========
##
host.port=http://127.0.0.1:8080
##
## ===
## JWT
## ===
##
## 86400000 = 1 day, 604800000 = 7 days
jwt.expiration=86400000
jwt.refresh-expiration=604800000
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
##
## ==========
## UUID Token
## ==========
##
## in minutes
uuid.token.expiration=15
##
## ====
## Mail
## ====
##
spring.mail.host=127.0.0.1
spring.mail.port=1025
spring.mail.username=hello
spring.mail.password=hello
spring.mail.properties.smtp.ssl.trust=*
spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
spring.mail.properties.smtp.connection-timeout=5000
spring.mail.properties.smtp.timeout=3000
spring.mail.properties.smtp.writetimeout=3000
##
## ====
## CORS
## ====
##
cors.allowed-origins=*
cors.allowed-headers=*
cors.allowed-methods=GET, POST, PATCH, DELETE
cors.allow-credentials=false
cors.max-age=3600
##
## =======
## OpenAPI
## =======
##
springdoc.swagger-ui.operations-sorter=method
springdoc.default-produces-media-type=application/json
##
## ======
## Stripe
## ======
##
stripe.key.secret=sk_test_51QfRhEDHREG5xZzTvGTh7P5gtTzdNjdAgA407ilFSZLSOwmvDKowjWQJ9Ea4PsopZAVkZQr8sgiNSi64YEoyxSQl00vB45XVGP
stripe.webhook.secret=whsec_eb5a665df0f3c21a266f6b64f1ceb8e226651058b1b909c9cda08246f96ceac7