-- Drop tables
DROP TABLE IF EXISTS favorite CASCADE;
DROP TABLE IF EXISTS transaction CASCADE;
DROP TABLE IF EXISTS house CASCADE;
DROP TABLE IF EXISTS apartment CASCADE;
DROP TABLE IF EXISTS land CASCADE;
DROP TABLE IF EXISTS ad CASCADE;
DROP TABLE IF EXISTS property CASCADE;
DROP TABLE IF EXISTS uuid_token CASCADE;
DROP TABLE IF EXISTS jwt_token CASCADE;
DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS address CASCADE;

-- Drop/create Sequences
DROP SEQUENCE IF EXISTS jwt_token_id_seq;
CREATE SEQUENCE jwt_token_id_seq AS integer;

ALTER SEQUENCE jwt_token_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS uuid_token_id_seq;
CREATE SEQUENCE uuid_token_id_seq AS integer;

ALTER SEQUENCE uuid_token_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS address_id_seq;
CREATE SEQUENCE address_id_seq AS integer;

ALTER SEQUENCE address_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS property_id_seq;
CREATE SEQUENCE property_id_seq AS integer;

ALTER SEQUENCE property_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS ad_id_seq;
CREATE SEQUENCE ad_id_seq AS integer;

ALTER SEQUENCE ad_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS land_id_seq;
CREATE SEQUENCE land_id_seq AS integer;

ALTER SEQUENCE land_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS apartment_id_seq;
CREATE SEQUENCE apartment_id_seq AS integer;

ALTER SEQUENCE apartment_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS house_id_seq;
CREATE SEQUENCE house_id_seq AS integer;

ALTER SEQUENCE house_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS contract_id_seq;
CREATE SEQUENCE contract_id_seq AS integer;

ALTER SEQUENCE contract_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS transaction_id_seq;
CREATE SEQUENCE transaction_id_seq AS integer;

ALTER SEQUENCE transaction_id_seq OWNER TO postgres;

DROP SEQUENCE IF EXISTS favorite_id_seq;
CREATE SEQUENCE favorite_id_seq AS integer;

ALTER SEQUENCE favorite_id_seq OWNER TO postgres;

-- Create tables
CREATE TABLE address
(
    id            bigint DEFAULT nextval('hs.address_id_seq'::regclass) NOT NULL,
    county        varchar(56)                                           NOT NULL,
    city          varchar(56)                                           NOT NULL,
    street_name   varchar(56)                                           NOT NULL,
    street_number integer                                               NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE address
    OWNER TO postgres;

ALTER SEQUENCE address_id_seq OWNED BY address.id;

CREATE TABLE contract
(
    id         bigint    DEFAULT nextval('hs.contract_id_seq'::regclass) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP                       NOT NULL,
    terms      varchar(1024)                                             NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE contract
    OWNER TO postgres;

ALTER SEQUENCE contract_id_seq OWNED BY contract.id;

CREATE TABLE app_user
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmed_at timestamp(6),
    created_at   timestamp(6) NOT NULL,
    email        varchar(64)  NOT NULL UNIQUE,
    first_name   varchar(32)  NOT NULL,
    is_enabled   boolean      NOT NULL,
    is_locked    boolean      NOT NULL,
    last_name    varchar(32)  NOT NULL,
    password     varchar(64)  NOT NULL,
    role         varchar(10)  NOT NULL CHECK (role IN ('USER', 'ADMIN', 'REALTOR')),
    updated_at   timestamp(6) NOT NULL
);

ALTER TABLE app_user
    OWNER TO postgres;

CREATE TABLE jwt_token
(
    id         bigint    DEFAULT nextval('hs.jwt_token_id_seq'::regclass) NOT NULL,
    token      varchar(256)                                               NOT NULL UNIQUE,
    is_revoked boolean   DEFAULT false                                    NOT NULL,
    is_expired boolean   DEFAULT false                                    NOT NULL,
    created_at timestamp DEFAULT now()                                    NOT NULL,
    user_id    bigint                                                     NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES app_user
);

ALTER TABLE jwt_token
    OWNER TO postgres;

ALTER SEQUENCE jwt_token_id_seq OWNED BY jwt_token.id;

CREATE TABLE uuid_token
(
    id         bigint    DEFAULT nextval('hs.uuid_token_id_seq'::regclass) NOT NULL,
    token      varchar(64)                                                 NOT NULL UNIQUE,
    created_at timestamp DEFAULT now()                                     NOT NULL,
    expires_at timestamp                                                   NOT NULL,
    user_id    bigint                                                      NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES app_user
);

ALTER TABLE uuid_token
    OWNER TO postgres;

ALTER SEQUENCE uuid_token_id_seq OWNED BY uuid_token.id;

CREATE TABLE property
(
    id         bigint  DEFAULT nextval('hs.property_id_seq'::regclass) NOT NULL,
    is_active  boolean DEFAULT true                                    NOT NULL,
    area       integer                                                 NOT NULL,
    user_id    bigint                                                  NOT NULL,
    address_id bigint                                                  NOT NULL,
    category   varchar(50)                                             NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address,
    FOREIGN KEY (user_id) REFERENCES app_user
);

ALTER TABLE property
    OWNER TO postgres;

ALTER SEQUENCE property_id_seq OWNED BY property.id;

CREATE TABLE ad
(
    id          bigint    DEFAULT nextval('hs.ad_id_seq'::regclass) NOT NULL,
    created_at  timestamp DEFAULT CURRENT_TIMESTAMP                 NOT NULL,
    title       varchar(64)                                         NOT NULL,
    description varchar(256)                                        NOT NULL,
    status      varchar(32)                                         NOT NULL,
    category    varchar(32)                                         NOT NULL,
    price       numeric(14, 2)                                      NOT NULL,
    owner_id    bigint                                              NOT NULL,
    realtor_id  bigint                                              NOT NULL,
    property_id bigint                                              NOT NULL,
    is_active   boolean   DEFAULT false,
    PRIMARY KEY (id),
    FOREIGN KEY (property_id) REFERENCES property,
    FOREIGN KEY (owner_id) REFERENCES app_user,
    FOREIGN KEY (realtor_id) REFERENCES app_user
);

ALTER TABLE ad
    OWNER TO postgres;

ALTER SEQUENCE ad_id_seq OWNED BY ad.id;

CREATE TABLE land
(
    id        bigint DEFAULT nextval('hs.land_id_seq'::regclass) NOT NULL PRIMARY KEY,
    land_type varchar(32)                                        NOT NULL,
    FOREIGN KEY (id) REFERENCES property
);

ALTER TABLE land
    OWNER TO postgres;

ALTER SEQUENCE land_id_seq OWNED BY land.id;

CREATE TABLE apartment
(
    id               bigint DEFAULT nextval('hs.apartment_id_seq'::regclass) NOT NULL PRIMARY KEY,
    build_year       integer                                                 NOT NULL,
    rooms_number     integer                                                 NOT NULL,
    bathrooms_number integer                                                 NOT NULL,
    partitioning     varchar(32)                                             NOT NULL,
    FOREIGN KEY (id) REFERENCES property
);

ALTER TABLE apartment
    OWNER TO postgres;

ALTER SEQUENCE apartment_id_seq OWNED BY apartment.id;

CREATE TABLE house
(
    id               bigint DEFAULT nextval('hs.house_id_seq'::regclass) NOT NULL PRIMARY KEY,
    build_year       integer                                             NOT NULL,
    floors_number    integer                                             NOT NULL,
    rooms_number     integer                                             NOT NULL,
    bathrooms_number integer                                             NOT NULL,
    FOREIGN KEY (id) REFERENCES property
);

ALTER TABLE house
    OWNER TO postgres;

ALTER SEQUENCE house_id_seq OWNED BY house.id;

CREATE TABLE transaction
(
    id             bigint         DEFAULT nextval('hs.transaction_id_seq'::regclass) NOT NULL PRIMARY KEY,
    type           varchar(32)                                                       NOT NULL,
    date           timestamp      DEFAULT CURRENT_TIMESTAMP                          NOT NULL,
    price          numeric(14, 2)                                                    NOT NULL CHECK (price >= 0),
    ad_id          bigint                                                            NOT NULL,
    customer_id    bigint                                                            NOT NULL,
    contract_id    bigint                                                            NOT NULL,
    payment_status varchar(32)    DEFAULT 'PENDING'                                  NOT NULL,
    commission     numeric(14, 2) DEFAULT 0                                          NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES ad ON DELETE RESTRICT,
    FOREIGN KEY (contract_id) REFERENCES contract ON DELETE RESTRICT,
    FOREIGN KEY (customer_id) REFERENCES app_user
);

ALTER TABLE transaction
    OWNER TO postgres;

ALTER SEQUENCE transaction_id_seq OWNED BY transaction.id;

CREATE TABLE favorite
(
    id       bigint  DEFAULT nextval('hs.favorite_id_seq'::regclass) NOT NULL PRIMARY KEY,
    is_added boolean DEFAULT true                                    NOT NULL,
    user_id  bigint                                                  NOT NULL,
    ad_id    bigint                                                  NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES ad,
    FOREIGN KEY (user_id) REFERENCES app_user
);

ALTER TABLE favorite
    OWNER TO postgres;

ALTER SEQUENCE favorite_id_seq OWNED BY favorite.id;
